name: Release
on:
  workflow_dispatch:
#   push:
#     branches:
#       - master
#       - develop
#     tags:
#       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fortivpn-socks5

    steps:
      - uses: actions/checkout@v3.3.0

      - uses: docker/setup-qemu-action@v2.1.0
        id: qemu
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2.2.1

      - name: Build and push
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u "$USERNAME" --password-stdin <<< "$PASSWORD"
          tag=$(date -u +%Y%m%d)
          docker buildx build --platform="${{ steps.qemu.outputs.platforms }}" --push -t "yulonger/docker-fortivpn-socks5-aarch64:$tag" .
          rm -rf ~/.docker
          
          
          
          
          
